# -*- coding: utf-8 -*-
"""Put this repo's Shogun tools into the existing 'Crescent Tools' menu.

MotionBuilder's menu is built at startup by:
    Documents\\MB\\<version>\\config\\PythonStartup\\cre_menu.py
which scans Documents\\MB\\<version>\\config\\Scripts\\Crescent\\ and turns
every sub-folder into a sub-menu and every .py inside it into a menu item
(run with FBApplication().ExecuteScript).

So this installer creates a 'Shogun' sub-folder there and writes one small
launcher per tool. Each launcher puts this repo on sys.path and executes the
real script from the repo, so the repo stays the single source of truth - no
copies to keep in sync.

Result:  Crescent Tools > Shogun > Capture Control / Review Playback / ...

Run this file once (in MotionBuilder's Python Editor or plain Python), then
restart MotionBuilder for the menu to be rebuilt.

Set UNINSTALL = True to remove the launchers again.
"""
import os
import shutil

# ---------------------------------------------------------------------------
# Settings
# ---------------------------------------------------------------------------
# MotionBuilder versions to install into, as they appear under Documents\MB\.
MB_VERSIONS = ["2024"]

# Name of the sub-menu created under 'Crescent Tools'.
SUBMENU_NAME = "Shogun"

# Print what would happen without writing anything.
DRY_RUN = False

# Remove previously installed launchers instead of writing them.
UNINSTALL = False

# Menu label -> tool script in this repo.
#
# The label is the launcher's file name minus '.py', because that is what
# cre_menu.py shows. Careful: it builds the label with str.strip(".py"), which
# strips *any* leading/trailing '.', 'p' or 'y' - so a label must not end in
# 'p' or 'y' or it will be truncated ("Review Play" would show as "Review Pla").
TOOLS = [
    ("Capture Control", "shogun_capture_control_tool_p3.py"),
    ("Capture Name from CSV", "shogun_capture_name_csv_tool_p3.py"),
    ("Review Playback", "shogun_review_play_tool_p3.py"),
    ("Subject Groups", "shogun_subject_groups_tool_p3.py"),
]

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))

LAUNCHER_TEMPLATE = '''# -*- coding: utf-8 -*-
# Generated by install_crescent_menu_p3.py - do not edit here.
# Edit the tool in {tools_dir} and re-run the installer.
import os
import sys

from pyfbsdk import FBApplication, FBMessageBox

TOOLS_DIR = r"{tools_dir}"
TOOL_SCRIPT = os.path.join(TOOLS_DIR, "{script}")

if TOOLS_DIR not in sys.path:
    sys.path.insert(0, TOOLS_DIR)

if os.path.isfile(TOOL_SCRIPT):
    FBApplication().ExecuteScript(TOOL_SCRIPT)
else:
    FBMessageBox("Shogun tools",
                 "Tool script not found:\\n{{0}}\\n\\n"
                 "Re-run install_crescent_menu_p3.py if the repo moved."
                 .format(TOOL_SCRIPT),
                 "OK", None, None)
'''


def crescent_dir(version):
    """Documents\\MB\\<version>\\config\\Scripts\\Crescent for this user."""
    return os.path.join(os.path.expanduser("~"), "Documents", "MB", version,
                        "config", "Scripts", "Crescent")


def bad_menu_label(label):
    """True if cre_menu.py's str.strip('.py') would truncate this label.

    strip() removes every leading and trailing character that is one of
    '.', 'p' or 'y', so a label is safe only if neither end is one of those.
    """
    if not label:
        return True
    return label[0] in ".py" or label[-1] in ".py"


def check_tools_exist():
    missing = [script for _label, script in TOOLS
               if not os.path.isfile(os.path.join(TOOLS_DIR, script))]
    return missing


def install_for_version(version):
    base = crescent_dir(version)
    if not os.path.isdir(base):
        print("  SKIP {0}: no Crescent folder at {1}".format(version, base))
        return False

    target = os.path.join(base, SUBMENU_NAME)

    if UNINSTALL:
        if not os.path.isdir(target):
            print("  {0}: nothing to remove ({1} does not exist)".format(version, target))
            return False
        print("  {0}: removing {1}".format(version, target))
        if not DRY_RUN:
            shutil.rmtree(target)
        return True

    print("  {0}: {1}".format(version, target))
    if not DRY_RUN and not os.path.isdir(target):
        os.makedirs(target)

    for label, script in TOOLS:
        if bad_menu_label(label):
            print("     ! '{0}' would be truncated in the menu - rename it".format(label))
            continue
        launcher = os.path.join(target, label + ".py")
        content = LAUNCHER_TEMPLATE.format(tools_dir=TOOLS_DIR, script=script)
        print("     {0}  ->  {1}".format(label, script))
        if not DRY_RUN:
            with open(launcher, "w", encoding="utf-8") as handle:
                handle.write(content)
    return True


def main():
    action = "Uninstalling" if UNINSTALL else "Installing"
    print("{0} the Shogun tools menu{1}".format(
        action, "  [DRY RUN - nothing written]" if DRY_RUN else ""))
    print("Repo: {0}".format(TOOLS_DIR))

    if not UNINSTALL:
        missing = check_tools_exist()
        if missing:
            print("ERROR: these tool scripts are missing from the repo:")
            for script in missing:
                print("  - {0}".format(script))
            return

    touched = 0
    for version in MB_VERSIONS:
        if install_for_version(version):
            touched += 1

    if touched == 0:
        print("Nothing was changed.")
        return

    if UNINSTALL:
        print("Done. Restart MotionBuilder to rebuild the menu.")
    else:
        print("Done. Restart MotionBuilder, then use:")
        print("  Crescent Tools > {0} > ...".format(SUBMENU_NAME))


main()
